version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: project-kis-user
      POSTGRES_PASSWORD: project-kis-password
      POSTGRES_DB: tododb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9000:8080"
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
      ADMINER_DESIGN: dracula

volumes:
  db_data:
